### ISSUE TITLE
  recent ( German zuletzt) -function stayed frozen, if creating 100 tiddler a day.

### ISSUE THREAD

**Issue by Paralullus** [pmario/TiddlyWiki5#5]
### Describe the bug

Hello there, thanks for maintain this valuable piece of Freedom.
I came from MoinMoinWiki and have had about to import about 500 pages, what I did one by one by hand, last week -36-.
Of each created entry in the MoinmoinWiki I open the last text page with xed, copy it, open a new tiddler and insert it there.

September 6.7. 8.  i did  import a lot , maybe creating 80 - 100 tiddler every day.
Now i discovered that the function recent / in German zuletzt / not work properly. It seems frozen. 

So i take an new empty German TiddlyWiki site and imported all the created tiddlers with it's Import-function. Which, by the way, is going great. . And the recent / zuletzt function works on September 13. . But only one time. After it, it was frozen again.
When I seek for a solution I found in the shadows a tiddler its name $:/core/Filters/RecentTiddlers. A limit of 50 has been set.
I set it to 150, save. reboot. Nothing new was displayed, the recent / zuletzt function remained frozen

I am not in the IT business, but i play with computers sins 1985. So installed sublime text and have a look inside TiddlyWiki.html
On seven places there is a name RecentTiddlers, as Filters/RecentTiddlers. But i can not figure out what I have to change.

Maybe the timestamp/Zeitstempel?  It is set to off/aus.

I use Linux Mint 20.3 Cinnamon.

### Expected behavior

**What is to change to make the  recent / zuletzt function  work  correct, even i work hard and have new 200 tiddlers on one day?**

### To Reproduce

1. Make 80 -100 Tiddler one day
2. Second day make 80 -100 Tiddler again
3. Third day make three Tiddlers 
4. What was the seconds name? 
5. Click on Recent 
6. It is frozen to first or/and second days Tiddlers.
    And does not show the current tiddlers from day three.

### TiddlyWiki Configuration

TiddlyWiki Version | 5.2.3

- Saving mechanism: like every hour I use this red button
- Plugins installed: only what comes with the German edition

- Desktop: Cinnamon
- OS: Linux Mint 20.3 
- Firefox 104.0.2 (64-Bit)

**Comment by pmario** [comment]
Hi, 
The main repository to create issues is https://github.com/Jermolene/TiddlyWiki5/issues .. But we can stay here. 

You should have a look at the "right sidebar" -> Mehr -> Alle tab. ... Are all tiddlers there?

The recent tab should only show the last 100 tiddlers which have a modified field ... If the modified field is missing, they won't show up in the "Zuletzt" tab

If you set the Zeitstempel to Aus .. there will be a problem. It doesn't set the modified field. ....

Since the Zuletzt tab by default is set to limit 100 and you import more than 100 tiddlers a day, you will only see 1 day .. That's a bit strange, but expected. 

Have a look at Mehr -> Alle ... It should show everything. .. Or you may set the limit in the $:/core/Filters/RecentTiddlers higher. 

BUT

There is a reason, why the Recent tab has a limit. ... If you have several 1000 tiddlers, it can start to slow down the UI responsiveness, if the Recent tab is visible. ...

You have a "very special " case at the moment, where you import a lot of tiddlers per day. ... So it will probably only show 1 day. .. Once you start working with the wiki the Recent tab should "return" to "expected" behaviour ... 

Conclusion -- It seems to be no bug. I think it's expected.

**Comment by pmario** [comment]
>Of each created entry in the MoinmoinWiki I open the last text page with xed, copy it, open a new tiddler and insert it there.

I don't know the MoinmoinWiki wiki. Do they have an export format? TW could handle several input formats. .. So it may be possible to "keep" the created and modified fields, or may be other meta data, that may be important for you.

**Comment by Paralullus** [comment]
Thank you Mario for your participation in my question and your answers. And for maintaining the German edition and your videos.
First I want to email you, but I couldn't find your email address. Mine is noske.spandau at t-online.de

Let's assume my question is solved. I just turned on the timestamp. And the Recent function starts to work.
Why did I stop the timestamp?
I'd like to see the date a new tiddler is launched for as long as possible. Can be found > Manager > select tiddler > scroll down to field. Then read field: created.
So it doesn't make sense to stop the timestamp and have some solid side effects.
output is to be closed.
Have excellent times where ever you go.

**Comment by pmario** [comment]
>Have excellent times where ever you go.

Thank you. 

You could easily make it dynamic eg: If you edit the [$:/core/ui/SideBar/Recent](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FSideBar%2FRecent) tiddler and enter following text, you'll get a config tiddler with which you can make your limit higher or lower on demand. 

So if the limit config tiddler doesn't exist or is empty, it uses the default value. If you add 300 it will give you about 300 tiddlers. 

```
<$macrocall $name="timeline" limit={{$:/config/recent-limit}} format={{$:/language/RecentChanges/DateFormat}}/>

<$edit-text tag=input tiddler="$:/config/recent-limit" placeholder="limit default: 100"/>
```
